#!/usr/bin/env bash
set -euo pipefail

root=$(cd "$(dirname "$0")/.." && pwd)
users_lua="$root/openresty/users.lua"
out="$root/docker-compose.users.yml"
template="$root/templates/settings.yaml"

ids=()
while IFS= read -r id; do
  [[ -n $id ]] || continue
  ids+=("$id")
done < <(sed -nE "s/^[[:space:]]*([a-z0-9-]+)[[:space:]]*=[[:space:]]*['\"][^'\"]+['\"].*/\1/p" "$users_lua")

if [[ ${#ids[@]} -eq 0 ]]; then
  echo "openresty/users.lua: no user entries found" >&2
  exit 1
fi

{
  echo '# Generated by scripts/render-compose.sh from openresty/users.lua. Do not edit by hand.'
  echo 'services:'
  for id in "${ids[@]}"; do
    cat <<EOF
  dsh-${id}:
    image: docker-dsh:v1
    build: .
    working_dir: /workspace
    init: true
    restart: unless-stopped
    environment:
      DEEPSEEK_API_KEY: \${DEEPSEEK_API_KEY:-}
      MINIMAX_CN_API_KEY: \${MINIMAX_CN_API_KEY:-}
      TSX_TSCONFIG_PATH: /app/tsconfig.json
    volumes:
      - \${HARNESS_PATH:-../deepseek-harness}:/app:ro
      - ./users/${id}/dsh_home:/root/.dsh
      - ./skills:/root/.dsh/skills:ro
      - ./overlays:/shared:ro
      - ./users/${id}/workspace:/workspace
    command:
      - node
      - --import
      - /app/node_modules/tsx/dist/esm/index.mjs
      - /app/apps/cli/src/bin.ts
      - web
      - --patch
      - /shared/lan-bind.cordis.yml
      - --patch
      - /shared/shared-mcp.yml
      - --patch
      - /shared/whoami.cordis.yml
      - --patch
      - /shared/suppress-welcome.cordis.yml
      - --patch
      - /shared/hide-settings-sections.cordis.yml
      - --patch
      - /shared/default-workspace.cordis.yml
      - --patch
      - /shared/default-flat-list.cordis.yml
      - --patch
      - /shared/slash-skill-first.cordis.yml
      - --patch
      - /shared/workspace-html-preview.cordis.yml
      - --no-open
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - internal
EOF
    mkdir -p "$root/users/$id/dsh_home" "$root/users/$id/workspace"
    if [[ -f $template && ! -f $root/users/$id/dsh_home/settings.yaml ]]; then
      cp "$template" "$root/users/$id/dsh_home/settings.yaml"
    fi
  done
  cat <<'EOF'
networks:
  internal:
    driver: bridge
EOF
} >"$out"

echo "wrote $out (${ids[*]})"
